[package]
name = "typr"
version = "0.4.19"
edition = "2021"
authors = ["Fabrice Hategekimana <fab.hatege15@gmail.com>"]
description = "A superset of the legendary R"
license = "Apache-2.0"
repository = "https://github.com/fabriceHategekimana/typr"
keywords = ["R", "type-checker", "language", "transpiler"] 
readme = "README.md"

[dependencies]
nom = "8.0.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.133"
clap = { version = "4.5", features = ["derive"] }
thiserror = "2.0.12"
miette = { version = "7.6.0", features = ["fancy"] }
nom_locate = "5.0.0"
rpds = "1.1.1"
bincode = "1.3"
rustyline = "17.0.2"
syntect = "5.3.0"
extendr-api = "0.8.1"
anyhow = "1.0.100"
lsp-types = "0.94"
tower-lsp = "0.20"
tokio = { version = "1", features = ["full"] }
indexmap = { version = "2.13.0", features = ["serde"] }
tap = "1.0.1"
rand = "0.10.0"

